#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_remove_app_dependencies

#=================================================
# REMOVE FILES
#=================================================
systemctl stop ${app}.timer
systemctl disable ${app}.timer
ynh_remove_systemd_config --service=${app}
ynh_remove_systemd_config --service=${app}_check
ynh_remove_systemd_config --service=${app}_check_read_data
ynh_secure_remove "/etc/systemd/system/${app}.timer"
ynh_secure_remove "/etc/systemd/system/${app}_check.timer"
ynh_secure_remove "/etc/systemd/system/${app}_check_read_data.timer"
ynh_secure_remove "/usr/local/bin/backup-with-${app}"
ynh_secure_remove "/usr/local/bin/check-${app}"
ynh_secure_remove "/usr/local/bin/check-read-data-${app}"
ynh_secure_remove "/etc/yunohost/hooks.d/backup_method/05-${app}_app"
ynh_secure_remove "/etc/yunohost/hooks.d/backup_method/05-${app}_check_app"
ynh_secure_remove "/etc/yunohost/hooks.d/backup_method/05-${app}_check_read_data_app"

#=================================================
# REMOVE SSH CONFIG
#=================================================
sed -e "/Host ${server}/,+6d" /root/.ssh/config -i || true
