#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME
export final_path="/opt/yunohost/${app}"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_remove_app_dependencies

#=================================================
# REMOVE FILES
#=================================================
systemctl stop ${app}.timer
systemctl disable ${app}.timer
ynh_remove_systemd_config --service=${app}
ynh_remove_systemd_config --service=${app}_check
ynh_remove_systemd_config --service=${app}_check_read_data
ynh_secure_remove "/etc/systemd/system/${app}.timer"
ynh_secure_remove "/etc/systemd/system/${app}_check.timer"
ynh_secure_remove "/etc/systemd/system/${app}_check_read_data.timer"
ynh_secure_remove "/usr/local/bin/backup-with-${app}"
ynh_secure_remove "/etc/yunohost/hooks.d/backup_method/05-${app}_app"
ynh_secure_remove "${final_path}/check_method"
ynh_secure_remove "${final_path}/check-${app}"
ynh_secure_remove "${final_path}"

#=================================================
# REMOVE SSH CONFIG
#=================================================
sed -e "/Host ${server}/,+6d" /root/.ssh/config -i || true
