#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME
export final_path="/opt/yunohost/${app}"

#=================================================
# CHECK IF AN UPGRADE IS NEEDED
#=================================================
ynh_check_app_version_changed

#=================================================
# BACKUP BEFORE UPGRADE THEN ACTIVE TRAP
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade
ynh_clean_setup () {
	# restore it if the upgrade fails
	ynh_restore_upgradebackup
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors


if grep "restic.timer" /etc/yunohost/services.yml > /dev/null ; then
    yunohost service remove $app.timer
    systemctl enable $app.timer
    systemctl start $app.timer
fi

#=================================================
# INSTALL RESTIC
#=================================================
install_restic

#=================================================
# CONFIGURE SERVICES
#=================================================
ynh_add_systemd_config --service=${app} --template=systemd.service
ynh_configure systemd.timer "/etc/systemd/system/${app}.timer"
systemctl disable ${app}.service
systemctl enable ${app}.timer

#=================================================
# ACTIVATE BACKUP METHODS
#=================================================
ynh_script_progression --message="Activating backup methods"
mkdir -p /etc/yunohost/hooks.d/backup_method || true
mkdir -p /usr/share/yunohost/backup_method || true

#=================================================
# SETUP THE BACKUP METHOD
#=================================================
ynh_script_progression --message="Setting up backup methods"
ynh_configure backup_method "/etc/yunohost/hooks.d/backup_method/05-${app}_app"
ynh_configure check_method "${final_path}/check_method"

#=================================================
# SETUP LOG SCRIPT
#=================================================
ynh_script_progression --message="Setting up log script"
ynh_configure restic_log "${final_path}/restic_log"
chmod u+x "${final_path}/restic_log"
